<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Recipe.Domain\Recipe.Domain.csproj" />
    <ProjectReference Include="..\Recipe.Application\Recipe.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="CloudinaryDotNet" Version="1.28.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="GlobalUsings.cs" />
    <Compile Include="Models\RecipeDbContext.cs" />
    <Compile Include="..\Recipe.Application\Features\**\*Handler.cs" Link="Features\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="Services\EmailService.cs" />
    <Compile Include="Services\ImageService.cs" />
    <Compile Include="Services\JwtService.cs" />
    <Compile Include="Services\OtpService.cs" />
    <Compile Include="Handlers\PasswordHashing.cs" />
    <Compile Include="Migrations\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Handlers\EmailTemplates\OtpTemplate.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Handlers\EmailTemplates\WelcomeTemplate.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
